name: TerningPoint DesignSystem CI

on:
  push:
    branches: [ develop ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: "temurin"

      - name: Change gradlew permissions
        run: chmod +x gradlew

      - name: Create Local Properties
        run: touch local.properties

      - name: Set Local Properties
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL }}
          NATIVE_APP_KEY: ${{ secrets.NATIVE_APP_KEY }}
          NATIVEAPPKEY: ${{ secrets.NATIVEAPPKEY }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          AMPLITUDE_DEV_KEY: ${{ secrets.AMPLITUDE_DEV_KEY }}
          AMPLITUDE_PROD_KEY: ${{ secrets.AMPLITUDE_PROD_KEY }}
        run: |
          echo base.url=\"$BASE_URL\" >> local.properties
          echo test.base.url=\"$TEST_BASE_URL\" >> local.properties
          echo native.app.key=\"$NATIVE_APP_KEY\" >> local.properties
          echo nativeAppKey=\"$NATIVEAPPKEY\" >> local.properties
          echo release.keyAlias=\"$RELEASE_KEY_ALIAS\" >> local.properties
          echo release.keyPassword=\"$RELEASE_KEY_PASSWORD\" >> local.properties
          echo release.storeFile=\"$RELEASE_STORE_FILE\" >> local.properties
          echo release.storePassword=\"$RELEASE_STORE_PASSWORD\" >> local.properties
          echo amplitudeDevKey=\"$AMPLITUDE_DEV_KEY\" >> local.properties
          echo amplitudeProdKey=\"$AMPLITUDE_PROD_KEY\" >> local.properties

      - name: Build Documentation
        run: ./gradlew dokkaHtml

      - name: Deploy Documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          BRANCH: gh-pages
          FOLDER: core/build/dokka/html